# Generated by Django 5.2.5 on 2025-08-13 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='загаловка')),
                ('description', models.TextField(verbose_name='описание')),
                ('image', models.ImageField(upload_to='settings', verbose_name='фото')),
            ],
            options={
                'verbose_name': 'Библиотеки',
                'verbose_name_plural': 'Библиотеки',
            },
        ),
    ]
